allow retrieving proxy image using blob
chanzuckerberg/docs-editor pull request #33
Opened 2021-05-03 23:37 UTC by silvestry

This PR adds option in runtime to proxy image by retrieving blob. This is driven by security consideration where the proxy endpoint needs to be called via post call, passing csrf token in header.

2021-05-03 23:47 UTC, hedgerwang requested changes

2021-05-03 23:47 UTC, hedgerwang commented on src/DocsSafeImage.js
> +      const objectURL = URL.createObjectURL(imageBlob);
This should skip if the component is no longer mounted.

2021-05-03 23:47 UTC, hedgerwang commented on src/DocsSafeImage.js
> +      this.setState({error: true, pending: false});
This should skip if the component is no longer mounted.

2021-05-03 23:47 UTC, hedgerwang commented on src/DocsSafeImage.js
> +    if (objectURL) {
`objectURL` is never updated once it's set. This won't work when `src` changes. 
The component should handle he case when `src` updates.

2021-05-03 23:47 UTC, hedgerwang commented on src/DocsSafeImage.js
> +      empty = true;
How is the variable `empty` be used? It does not seem doing anything.

2021-05-03 23:47 UTC, hedgerwang commented on src/DocsSafeImage.js
> +      const imageBlob = await runtime.getProxyImageBlob(src);
How would the UI look like while loading the blob?

2021-05-04 01:37 UTC, silvestry commented on src/DocsSafeImage.js
> +      empty = true;
This was part of original code on line 118 `return (error || empty) ?` and line 87 where it sets css `docs-safe-image-empty`

2021-05-04 01:44 UTC, silvestry commented on src/DocsSafeImage.js
> +    if (objectURL) {
Good catch. I totally missed this one. Will update `componentWillReceiveProps`

2021-05-04 02:13 UTC, silvestry commented on src/DocsSafeImage.js
> +    if (objectURL) {
And also updated `_getProxyImageObjectURL` on async return will check if src is still valid

2021-05-04 03:45 UTC, silvestry commented
@hedgerwang : Thanks for the review. I've updated per your excellent callouts - 1. check for unmount and 2. addressed change in src. Please kindly re-review. Thanks!

2021-05-04 04:15 UTC, silvestry commented on src/DocsSafeImage.js
> +      const imageBlob = await runtime.getProxyImageBlob(src);
There is a white box. Not ideal, but reasonable?

<img width="528" alt="Screen Shot 2021-05-03 at 9 14 31 PM" src="https://user-images.githubusercontent.com/40640760/116960254-b80ca980-ac54-11eb-814a-f265e060eedc.png">

2021-05-05 19:18 UTC, hedgerwang approved these changes

2021-05-05 19:18 UTC, hedgerwang commented on src/DocsSafeImage.js
> +        this._getProxyImageObjectURL(runtime, src);
Ideally, `render` should not have side-effect.
Instead, using life-cycle method to manage side-effects.

```
componentDidMount(): {
  this._maybeLoadObjectUrl();
}

componentDidUpdate(): {
  this._maybeLoadObjectUrl();
}

_maybeLoadObjectUrl() {
  const {src} = this.props;
  const {objectURL} = this.state;
  const {runtime} = this.context.docsContext;
  if (!objectURL && src && runtime && runtime.canProxyImageBlob(src)) {
    this._getProxyImageObjectURL(runtime, src);
  }  
}
```

2021-05-05 19:18 UTC, hedgerwang commented on src/DocsSafeImage.js
> +      const imageBlob = await runtime.getProxyImageBlob(src);
lgtm.

2021-05-07 18:14 UTC, merged